## spider.py
import scrapy
from quotes_js_scraper.items import QuoteItem
from scrapy_selenium import SeleniumRequest
from selenium.webdriver.common.by import By
from selenium.webdriver.support import expected_conditions as EC
from selenium.webdriver.support.ui import WebDriverWait

class QuotesSpider(scrapy.Spider):
    name = 'quotes_11'

    start_urls = [
        'https://www.twitch.tv/xRohat/about', 
'https://www.twitch.tv/Cellbit/about', 
'https://www.twitch.tv/MckyTV/about', 
'https://www.twitch.tv/H2P_Gucio/about', 
'https://www.twitch.tv/BastiGHG/about', 
'https://www.twitch.tv/Foolish/about', 
'https://www.twitch.tv/Etoiles/about', 
'https://www.twitch.tv/Roier/about', 
'https://www.twitch.tv/Philza/about', 
'https://www.twitch.tv/Tubbo/about', 
'https://www.twitch.tv/edizderbreite/about', 
'https://www.twitch.tv/HoneyPuu/about', 
'https://www.twitch.tv/Fabo/about', 
'https://www.twitch.tv/Bagi/about', 
'https://www.twitch.tv/NiklasWilson/about', 
'https://www.twitch.tv/vysotzky/about', 
'https://www.twitch.tv/SmallAnt/about', 
'https://www.twitch.tv/BadBoyHalo/about', 
'https://www.twitch.tv/peqitw/about', 
'https://www.twitch.tv/TinaKitten/about', 
'https://www.twitch.tv/Conterstine/about', 
'https://www.twitch.tv/LukiSteve/about', 
'https://www.twitch.tv/MokrySuchar/about', 
'https://www.twitch.tv/FarfadoxVEVO/about', 
'https://www.twitch.tv/Shadoune666/about', 
'https://www.twitch.tv/FitMC/about', 
'https://www.twitch.tv/EiMine77/about', 
'https://www.twitch.tv/Quackity/about', 
'https://www.twitch.tv/aypierre/about', 
'https://www.twitch.tv/다주 (dda_ju)/about', 
'https://www.twitch.tv/Feinberg/about', 
'https://www.twitch.tv/BreitenBerg/about', 
'https://www.twitch.tv/mehdideluxe/about', 
'https://www.twitch.tv/Wichtiger/about', 
'https://www.twitch.tv/악어 (jdm2088)/about', 
'https://www.twitch.tv/SEYYN/about', 
'https://www.twitch.tv/Cinemagrath/about', 
'https://www.twitch.tv/impulseSV/about', 
'https://www.twitch.tv/TwitchRivals/about', 
'https://www.twitch.tv/Adal/about', 
'https://www.twitch.tv/LinkTheMike/about', 
'https://www.twitch.tv/BTMC/about', 
'https://www.twitch.tv/TheGuill84/about', 
'https://www.twitch.tv/iskall85/about', 
'https://www.twitch.tv/Luzu/about', 
'https://www.twitch.tv/rewinside/about', 
'https://www.twitch.tv/PWGood/about', 
'https://www.twitch.tv/RaptorGamesXD1/about', 
'https://www.twitch.tv/EiMine24h/about', 
'https://www.twitch.tv/중력 (jungryeok)/about', 
'https://www.twitch.tv/lollolacustre/about', 
'https://www.twitch.tv/TangoTek/about', 
'https://www.twitch.tv/Linkzzey/about', 
'https://www.twitch.tv/JonBams/about', 
'https://www.twitch.tv/GommeHD/about', 
'https://www.twitch.tv/PearlescentMoon/about', 
'https://www.twitch.tv/Eldos/about', 
'https://www.twitch.tv/JeremyFrieser/about', 
'https://www.twitch.tv/ElRichMC/about', 
'https://www.twitch.tv/MissaSinfonia/about', 
'https://www.twitch.tv/GoodTimesWithScar/about', 
'https://www.twitch.tv/giaantv/about', 
'https://www.twitch.tv/ZAKl1k/about', 
'https://www.twitch.tv/CaptainSparklez/about', 
'https://www.twitch.tv/CastCrafter/about', 
'https://www.twitch.tv/TubboLIVE/about', 
'https://www.twitch.tv/xShatter/about', 
'https://www.twitch.tv/flowtives/about', 
'https://www.twitch.tv/JimmyBoyyy/about', 
'https://www.twitch.tv/GeorgeNotFound/about', 
'https://www.twitch.tv/nooreax/about', 
'https://www.twitch.tv/GTimeTV/about', 
'https://www.twitch.tv/scottonauta/about', 
'https://www.twitch.tv/ZakvielChannel/about', 
'https://www.twitch.tv/Sapnap/about', 
'https://www.twitch.tv/Couriway/about', 
'https://www.twitch.tv/hannahxxrose/about', 
'https://www.twitch.tv/fruitberries/about', 
'https://www.twitch.tv/Pirutastic/about', 
'https://www.twitch.tv/hypnotizd/about', 
'https://www.twitch.tv/Smajor/about', 
'https://www.twitch.tv/Alexby11/about', 
'https://www.twitch.tv/LostPhoenixWolf/about', 
'https://www.twitch.tv/Nofaxu/about', 
'https://www.twitch.tv/Xisuma/about', 
'https://www.twitch.tv/CapitanGatoo/about', 
'https://www.twitch.tv/X33N/about', 
'https://www.twitch.tv/Skizzleman/about', 
'https://www.twitch.tv/doogile/about', 
'https://www.twitch.tv/adrian1g__/about', 
'https://www.twitch.tv/Toshiruz/about', 
'https://www.twitch.tv/ZombieCleo/about', 
'https://www.twitch.tv/k4yfour/about', 
'https://www.twitch.tv/DanriqueTW/about', 
'https://www.twitch.tv/Nihachu/about', 
'https://www.twitch.tv/rendogtv/about', 
'https://www.twitch.tv/핑맨 (95pingman)/about', 
'https://www.twitch.tv/AutomattPL/about', 
'https://www.twitch.tv/flufftapes/about', 
'https://www.twitch.tv/MathoX/about', 
'https://www.twitch.tv/나나양 (nanayango3o)/about', 
'https://www.twitch.tv/youngpalas24/about', 
'https://www.twitch.tv/lala_style/about', 
'https://www.twitch.tv/Purpled/about', 
'https://www.twitch.tv/김남봉 (nambong94)/about', 
'https://www.twitch.tv/Neagari/about', 
'https://www.twitch.tv/GeminiTay/about', 
'https://www.twitch.tv/MLDEG/about', 
'https://www.twitch.tv/Nuvia_OuO/about', 
'https://www.twitch.tv/APPELKAAS/about', 
'https://www.twitch.tv/ChiChi/about', 
'https://www.twitch.tv/Jvnq/about', 
'https://www.twitch.tv/Longy/about', 
'https://www.twitch.tv/falsesymmetry/about', 
'https://www.twitch.tv/stan616/about', 
'https://www.twitch.tv/Crisgreen/about', 
'https://www.twitch.tv/Canadian_Dragon/about', 
'https://www.twitch.tv/TrymacsKaktusKoenig/about', 
'https://www.twitch.tv/Alcest_M/about', 
'https://www.twitch.tv/Hasvik/about', 
'https://www.twitch.tv/Generikb/about', 
'https://www.twitch.tv/Puddingb00m/about', 
'https://www.twitch.tv/Button/about', 
'https://www.twitch.tv/HBomb94/about', 
'https://www.twitch.tv/Pacey/about', 
'https://www.twitch.tv/Choke7/about', 
'https://www.twitch.tv/doutorbiscoito/about', 
'https://www.twitch.tv/UmildLive/about', 
'https://www.twitch.tv/hayd1_/about', 
'https://www.twitch.tv/slyde_minecraft/about', 
'https://www.twitch.tv/tommyinnit/about', 
'https://www.twitch.tv/Joehills/about', 
'https://www.twitch.tv/김마렌 (maren_0e077)/about', 
'https://www.twitch.tv/cubfan135/about', 
'https://www.twitch.tv/TheBakedDean/about', 
'https://www.twitch.tv/Nardc0/about', 
'https://www.twitch.tv/Mollu/about', 
'https://www.twitch.tv/양띵 (yd0821)/about', 
'https://www.twitch.tv/xMusti19/about', 
'https://www.twitch.tv/Bastet/about', 
'https://www.twitch.tv/WaxFraud/about', 
'https://www.twitch.tv/CallMeCarsonLIVE/about', 
'https://www.twitch.tv/Lvcyd/about', 
'https://www.twitch.tv/gkey/about', 
'https://www.twitch.tv/Guep/about', 
'https://www.twitch.tv/coldified/about', 
'https://www.twitch.tv/fehdubs/about', 
'https://www.twitch.tv/iJevin/about', 
'https://www.twitch.tv/Duncan/about', 
'https://www.twitch.tv/NAROY/about', 
'https://www.twitch.tv/TylorTurner/about', 
'https://www.twitch.tv/Greninja/about', 
'https://www.twitch.tv/nofearr1337/about', 
'https://www.twitch.tv/MuriloRevex/about', 
'https://www.twitch.tv/Secboba/about', 
'https://www.twitch.tv/FireBreathMan/about', 
'https://www.twitch.tv/towdan/about', 
'https://www.twitch.tv/VyneHellebore/about', 
'https://www.twitch.tv/HwithoutS/about', 
'https://www.twitch.tv/PrinceZamLIVE/about', 
'https://www.twitch.tv/ChosenArchitect/about', 
'https://www.twitch.tv/InTheLittleWood/about', 
'https://www.twitch.tv/beatriz/about', 
'https://www.twitch.tv/7rowl/about', 
'https://www.twitch.tv/emikotone/about', 
'https://www.twitch.tv/CinCityLive/about', 
'https://www.twitch.tv/QSMP/about', 
'https://www.twitch.tv/Matrixis/about', 
'https://www.twitch.tv/Facha/about', 
'https://www.twitch.tv/aimsey/about', 
'https://www.twitch.tv/Brahemic/about', 
'https://www.twitch.tv/TdLmc/about', 
'https://www.twitch.tv/Aurigas/about', 
'https://www.twitch.tv/Jamal_/about', 
'https://www.twitch.tv/Guaxinim/about', 
'https://www.twitch.tv/Daxlian/about', 
'https://www.twitch.tv/beaplays/about', 
'https://www.twitch.tv/Fuxelbau/about', 
'https://www.twitch.tv/VanishedTwo/about', 
'https://www.twitch.tv/NoaNoella/about', 
'https://www.twitch.tv/bobowgames/about', 
'https://www.twitch.tv/단군 (1983kej)/about', 
'https://www.twitch.tv/TheIceBlueBird/about', 
'https://www.twitch.tv/jorvp/about', 
'https://www.twitch.tv/Alfedov/about', 
'https://www.twitch.tv/WartinSal/about', 
'https://www.twitch.tv/Kippesoepje/about', 
'https://www.twitch.tv/zakl2k/about', 
'https://www.twitch.tv/Linahun/about', 
'https://www.twitch.tv/유키라_ (kira_baby2)/about', 
'https://www.twitch.tv/CentrahTV/about', 
'https://www.twitch.tv/G3TRAIL3D/about', 
'https://www.twitch.tv/Mr_Guinas/about', 
'https://www.twitch.tv/Pixlriffs/about', 
'https://www.twitch.tv/helenys333/about', 
'https://www.twitch.tv/Diffrent/about', 
'https://www.twitch.tv/GameTimeWithEric/about', 
'https://www.twitch.tv/Hoef___/about', 
'https://www.twitch.tv/TheCake404/about', 
'https://www.twitch.tv/DaveGuy_/about', 
'https://www.twitch.tv/Timmy_the_Otter/about', 
'https://www.twitch.tv/AlpZz_/about', 
'https://www.twitch.tv/모개 (cih190826)/about', 
'https://www.twitch.tv/obsidiantime/about', 
'https://www.twitch.tv/GOLRIVER_/about', 
'https://www.twitch.tv/PurpleGroundTTV/about', 
'https://www.twitch.tv/Diamkey/about', 
'https://www.twitch.tv/MikanTheCapybara/about', 
'https://www.twitch.tv/tadpole_milk_/about', 
'https://www.twitch.tv/Soaryn/about', 
'https://www.twitch.tv/dipbetw/about', 
'https://www.twitch.tv/sleepingrhys/about', 
'https://www.twitch.tv/darkosto/about', 
'https://www.twitch.tv/docm77LIVE/about', 
'https://www.twitch.tv/ShadowStone/about', 
'https://www.twitch.tv/luckeY/about', 
'https://www.twitch.tv/sublimiter/about', 
'https://www.twitch.tv/Blairadonna/about', 
'https://www.twitch.tv/MoDDyChat/about', 
'https://www.twitch.tv/Bez_LS/about', 
'https://www.twitch.tv/Josejuanjo/about', 
'https://www.twitch.tv/Antfrost/about', 
'https://www.twitch.tv/BruninhoSO7/about', 
'https://www.twitch.tv/Dominoe_Effect/about', 
'https://www.twitch.tv/owengejuicetv/about', 
'https://www.twitch.tv/HanakoAwing/about', 
'https://www.twitch.tv/LinkTijger/about', 
'https://www.twitch.tv/Sh4dowfi4sh/about', 
'https://www.twitch.tv/lamKOVA/about', 
'https://www.twitch.tv/Clym/about', 
'https://www.twitch.tv/Flothar/about', 
'https://www.twitch.tv/ErenBlaze/about', 
'https://www.twitch.tv/김나앨 (llnael)/about', 
'https://www.twitch.tv/Luh/about', 
'https://www.twitch.tv/DavincstyleGames/about', 
'https://www.twitch.tv/silverrruns/about', 
'https://www.twitch.tv/NotSoClutch/about', 
'https://www.twitch.tv/thejocraft_live/about', 
'https://www.twitch.tv/KenoN__/about', 
'https://www.twitch.tv/RogerMinemu/about', 
'https://www.twitch.tv/sweatgod/about', 
'https://www.twitch.tv/Taneesha/about', 
'https://www.twitch.tv/LJoga/about', 
'https://www.twitch.tv/Roesalie/about', 
'https://www.twitch.tv/Nagatow/about', 
'https://www.twitch.tv/66sombra66/about', 
'https://www.twitch.tv/SandwichLord_/about', 
'https://www.twitch.tv/シャークん (sharkenwt)/about', 
'https://www.twitch.tv/도라희ㅀ (doraheee_)/about', 
'https://www.twitch.tv/S0ldierbr/about', 


        # Add more URLs as strings separated by commas
    ]

    def start_requests(self):
        # Iterate over the list of URLs and yield SeleniumRequest for each
        for url in self.start_urls:
            yield SeleniumRequest(url=url, callback=self.parse)



    def parse(self, response):
        link = QuoteItem()
    # Adjust the CSS selector to target the class name
    # Note: Since class names containing spaces indicate multiple classes, replace spaces with dots.
        for links in response.css('a[data-test-selector="link_url_test_selector"]::attr(href)').getall():
        # You might want to extract the href attribute as well
            for link in links:
                yield {'url': link}

    def closed(self, reason):
        # Close the WebDriver when done
        self.driver.quit()